version: '2'
services:

# 关注点
# 1. 如何注入系统配置到容器中 环境变量注入
# 2. 端口的映射关系
# 3. 文件的映射

  orderer.educhain.accurchain.com:
    container_name: orderer.educhain.accurchain.com
    image: hyperledger/fabric-orderer:amd64-1.2.1
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info # general.loglevel: debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0 # 服务暴露地址
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block # 注入创世区块
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp # 证书相关
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050 # 17050:7050
    volumes:
        #- ./config/:/etc/hyperledger/config
        - ./config/genesis.block:/etc/hyperledger/config/genesis.block
        - ./crypto-config/ordererOrganizations/educhain.accurchain.com/orderers/orderer.educhain.accurchain.com/:/etc/hyperledger/orderer

#  peer.base: # peer的公共服务
#    image: hyperledger/fabric-peer:amd64-1.2.1
#    environment: # 前缀：CORE
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock # docker的服务端注入
#      - CORE_LOGGING_PEER=info
#      - CORE_CHAINCODE_LOGGING_LEVEL=INFO
#      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp # msp证书（节点证书）
#      - CORE_LEDGER_STATE_STATEDATABASE=goleveldb # 状态数据库的存储引擎（or CouchDB）
#      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=deploy_default # cc与peer节点使用同一个网络
#    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
#    command: peer node start

  peer0.org0.educhain.accurchain.com:
#    extends:
#      service: peer.base
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.org0.educhain.accurchain.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org0.educhain.accurchain.com
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_ADDRESS=peer0.org0.educhain.accurchain.com:7051
    ports:
      - 7051:7051 # grpc服务端口
      - 7053:7053 # eventhub端口
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.educhain.accurchain.com/peers/peer0.org0.educhain.accurchain.com:/etc/hyperledger/peer
    depends_on:
      - orderer.educhain.accurchain.com

  peer1.org0.educhain.accurchain.com:
#    extends:
#      service: peer.base
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.org0.educhain.accurchain.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org0.educhain.accurchain.com
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_ADDRESS=peer1.org0.educhain.accurchain.com:7051
    ports:
      - 17051:7051
      - 17053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.educhain.accurchain.com/peers/peer1.org0.educhain.accurchain.com:/etc/hyperledger/peer
    depends_on:
      - orderer.educhain.accurchain.com

  peer0.org1.educhain.accurchain.com:
#    extends:
#      service: peer.base
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.org1.educhain.accurchain.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.educhain.accurchain.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.educhain.accurchain.com:7051
    ports:
      - 27051:7051
      - 27053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.educhain.accurchain.com/peers/peer0.org1.educhain.accurchain.com:/etc/hyperledger/peer
    depends_on:
      - orderer.educhain.accurchain.com

  peer1.org1.educhain.accurchain.com:
#    extends:
#      service: peer.base
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.org1.educhain.accurchain.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.educhain.accurchain.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.educhain.accurchain.com:7051
    ports:
      - 37051:7051
      - 37053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.educhain.accurchain.com/peers/peer1.org1.educhain.accurchain.com:/etc/hyperledger/peer
    depends_on:
      - orderer.educhain.accurchain.com

  peer0.org2.educhain.accurchain.com:
#    extends:
#      service: peer.base
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.org2.educhain.accurchain.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.educhain.accurchain.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.educhain.accurchain.com:7051
    ports:
      - 47051:7051
      - 47053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.educhain.accurchain.com/peers/peer0.org2.educhain.accurchain.com:/etc/hyperledger/peer
    depends_on:
      - orderer.educhain.accurchain.com

  peer1.org2.educhain.accurchain.com:
#    extends:
#      service: peer.base
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.org2.educhain.accurchain.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.educhain.accurchain.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.educhain.accurchain.com:7051
    ports:
      - 57051:7051
      - 57053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.educhain.accurchain.com/peers/peer1.org2.educhain.accurchain.com:/etc/hyperledger/peer
    depends_on:
      - orderer.educhain.accurchain.com

  cli: # peer节点客户端 交易都是从客户端发起 需要用到User证书
    container_name: cli
    image: hyperledger/fabric-tools:amd64-1.2.1
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.educhain.accurchain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/org1.educhain.accurchain.com/users/Admin@org1.educhain.accurchain.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: /bin/bash
    volumes:
      - ./../chaincode:/opt/gopath/src/github.com/chaincode # 链码路径注入
      - ./config:/etc/hyperledger/config
      - ./crypto-config/peerOrganizations/:/etc/hyperledger/peer
