# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.educhain.accurchain.com:
  peer0.org0.educhain.accurchain.com:
  peer1.org0.educhain.accurchain.com:
  peer0.org1.educhain.accurchain.com:
  peer1.org1.educhain.accurchain.com:
  peer0.org2.educhain.accurchain.com:
  peer1.org2.educhain.accurchain.com:
  cli:

networks:
  byfn:

services:

  orderer.educhain.accurchain.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.educhain.accurchain.com
    container_name: orderer.educhain.accurchain.com
    networks:
      - byfn

  peer0.org0.educhain.accurchain.com:
    container_name: peer0.org0.educhain.accurchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org0.educhain.accurchain.com
    networks:
      - byfn

  peer1.org0.educhain.accurchain.com:
    container_name: peer1.org0.educhain.accurchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org0.educhain.accurchain.com
    networks:
      - byfn

  peer0.org1.educhain.accurchain.com:
    container_name: peer0.org1.educhain.accurchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.educhain.accurchain.com
    networks:
      - byfn

  peer1.org1.educhain.accurchain.com:
    container_name: peer1.org1.educhain.accurchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.educhain.accurchain.com
    networks:
      - byfn

  peer0.org2.educhain.accurchain.com:
    container_name: peer0.org2.educhain.accurchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.educhain.accurchain.com
    networks:
      - byfn

  peer1.org2.educhain.accurchain.com:
    container_name: peer1.org2.educhain.accurchain.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.educhain.accurchain.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=sys-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.educhain.accurchain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      #- CORE_PEER_TLS_ENABLED=true
      #- CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      #- CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      #- CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      #- CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.educhain.accurchain.com/users/Admin@org1.educhain.accurchain.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./crypto-config/peerOrganizations/:/etc/hyperledger/peer
        - ./config:/etc/hyperledger/config
    depends_on:
        - orderer.educhain.accurchain.com
        - peer0.org0.educhain.accurchain.com
        - peer1.org0.educhain.accurchain.com
        - peer0.org1.educhain.accurchain.com
        - peer1.org1.educhain.accurchain.com
        - peer0.org2.educhain.accurchain.com
        - peer1.org2.educhain.accurchain.com
    networks:
      - byfn
