# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.test.com:
  node1.Organization1.test.com:
  node2.Organization1.test.com:
  node1.Organization2.test.com:
  node2.Organization2.test.com:
  node1.Organization3.test.com:
  node2.Organization3.test.com:

networks:
  byfn:

services:

  orderer.test.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.test.com
    container_name: orderer.test.com
    networks:
      - byfn

  node1.Organization1.test.com:
    container_name: node1.Organization1.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: node1.Organization1.test.com
    networks:
      - byfn
  node2.Organization1.test.com:
    container_name: node2.Organization1.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: node2.Organization1.test.com
    networks:
      - byfn
  node1.Organization2.test.com:
    container_name: node1.Organization2.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: node1.Organization2.test.com
    networks:
      - byfn
  node2.Organization2.test.com:
    container_name: node2.Organization2.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: node2.Organization2.test.com
    networks:
      - byfn
  node1.Organization3.test.com:
    container_name: node1.Organization3.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: node1.Organization3.test.com
    networks:
      - byfn
  node2.Organization3.test.com:
    container_name: node2.Organization3.test.com
    extends:
      file:  base/docker-compose-base.yaml
      service: node2.Organization3.test.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=syschannel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=node1.Organization1.test.com:7051
      - CORE_PEER_LOCALMSPID=Organization1MSP
#      - CORE_PEER_TLS_ENABLED=true
#      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
#      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
#      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Organization1.test.com/users/Admin@Organization1.test.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
#        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
        - orderer.test.com
        - node1.Organization1.test.com
        - node2.Organization1.test.com
        - node1.Organization2.test.com
        - node2.Organization2.test.com
        - node1.Organization3.test.com
        - node2.Organization3.test.com
    networks:
      - byfn
